const Response = require("../models/Response");
const ChatLog = require("../models/ChatLog");
const { dispatchForAccident } = require("./dispatchService");
const { emitToRole, emitToUser } = require("./socketManager");

const activeTimers = new Map();

const keyFor = (accidentId, userId) => `${String(accidentId)}:${String(userId)}`;

exports.startSafetyTimer = ({ accidentId, userId, timeoutMs }) => {
  const key = keyFor(accidentId, userId);

  if (activeTimers.has(key)) {
    clearTimeout(activeTimers.get(key));
  }

  const startedAt = Date.now();

  const timer = setTimeout(async () => {
    activeTimers.delete(key);

    const existing = await Response.findOne({ accidentId, userId });
    if (existing) return;

    await Response.create({
      accidentId,
      userId,
      responseType: "No Response",
      responseTimeMs: Date.now() - startedAt,
      autoGenerated: true,
    });

    await ChatLog.create({
      accidentId,
      userId,
      senderType: "user",
      message: "No response received",
      responseType: "No Response",
    });

    emitToUser(userId, "chatbot:timeout", {
      accidentId,
      message: "No response received. Emergency dispatch initiated.",
    });

    const introLog = await ChatLog.create({
      accidentId,
      userId,
      senderType: "system",
      message: "Admin support chat opened automatically. Share your condition when you are able.",
      responseType: "Chat",
    });

    emitToUser(userId, "chat:message", { message: introLog });
    emitToRole("admin", "chat:message", { message: introLog });

    await dispatchForAccident({
      accidentId,
      reason: "No user response within timeout",
      assignedBy: "system",
    });
  }, timeoutMs);

  activeTimers.set(key, timer);
};

exports.stopSafetyTimer = ({ accidentId, userId }) => {
  const key = keyFor(accidentId, userId);
  if (activeTimers.has(key)) {
    clearTimeout(activeTimers.get(key));
    activeTimers.delete(key);
  }
};
