const fs = require("fs");
const path = require("path");
const { validationResult } = require("express-validator");
const Response = require("../models/Response");
const AccidentEmulation = require("../models/AccidentEmulation");
const { dispatchForAccident } = require("../services/dispatchService");
const { createAccidentAndTriggerWorkflow } = require("../services/accidentWorkflowService");
const { analyzeCitizenReportMedia } = require("../services/reportMediaAnalysisService");
const { emitToRole } = require("../services/socketManager");

const uploadsRoot = path.join(__dirname, "..", "uploads", "incident-media");
fs.mkdirSync(uploadsRoot, { recursive: true });
const AUTO_DISPATCH_SEVERITY_THRESHOLD = 60;

exports.createFromDetectionEngine = async (req, res, next) => {
  try {
    const expectedKey = process.env.DETECTION_API_KEY;
    if (expectedKey && req.headers["x-detection-key"] !== expectedKey) {
      return res.status(401).json({ success: false, message: "Invalid detection key" });
    }

    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({ success: false, errors: errors.array() });
    }

    const accident = await createAccidentAndTriggerWorkflow({
      payload: req.body,
      source: "external_engine",
    });

    res.status(201).json({ success: true, accident });
  } catch (error) {
    next(error);
  }
};

exports.getMyAccidents = async (req, res, next) => {
  try {
    const responses = await Response.find({ userId: req.user._id })
      .populate("accidentId")
      .sort({ createdAt: -1 })
      .lean();

    const history = responses.map((r) => ({
      responseId: r._id,
      responseType: r.responseType,
      autoGenerated: r.autoGenerated,
      createdAt: r.createdAt,
      accident: r.accidentId,
    }));

    res.json({ success: true, history });
  } catch (error) {
    next(error);
  }
};

exports.manualCreateAccident = async (req, res, next) => {
  try {
    const accident = await createAccidentAndTriggerWorkflow({
      payload: { ...req.body, confidenceScore: req.body.confidenceScore ?? 1 },
      source: "manual",
    });

    await dispatchForAccident({
      accidentId: accident._id,
      reason: "Manual dispatch created by admin",
      assignedBy: "admin",
    });

    res.status(201).json({ success: true, accident });
  } catch (error) {
    next(error);
  }
};

exports.submitCitizenIncident = async (req, res, next) => {
  try {
    if (!req.file) {
      return res.status(400).json({ success: false, message: "Image or video file is required" });
    }

    const latitude = Number(req.body.latitude);
    const longitude = Number(req.body.longitude);

    if (!Number.isFinite(latitude) || !Number.isFinite(longitude)) {
      return res.status(400).json({ success: false, message: "Valid latitude and longitude are required" });
    }

    const mediaType = String(req.file.mimetype || "");
    const isImage = mediaType.startsWith("image/");
    const isVideo = mediaType.startsWith("video/");
    let analysis = null;

    if (isImage || isVideo) {
      try {
        analysis = await analyzeCitizenReportMedia({
          filePath: req.file.path,
          mimeType: req.file.mimetype || "",
        });
      } catch (error) {
        console.error("Citizen report media analysis failed:", error.message);
      }
    }

    const mediaUrl = `/uploads/incident-media/${path.basename(req.file.path)}`;
    const severity = analysis?.severity || req.body.severity || "Medium";
    const confidenceScore = Number(analysis?.confidenceScore ?? req.body.confidenceScore ?? 0.6);
    const normalizedConfidenceScore = Math.max(0, Math.min(1, confidenceScore));
    const severityPercentage = Math.max(
      0,
      Math.min(
        100,
        Number(analysis?.severityPercentage ?? analysis?.signals?.severityPercentage ?? 0)
      )
    );
    const reportPayload = {
      latitude,
      longitude,
      severity,
      confidenceScore: normalizedConfidenceScore,
      cameraId: "",
      address: req.body.address || "",
      metadata: {
        source: "citizen_upload",
        citizenDescription: req.body.description || "",
        media: {
          kind: isImage ? "image" : "video",
          mimeType: req.file.mimetype,
          originalName: req.file.originalname,
          fileName: path.basename(req.file.path),
          url: mediaUrl,
        },
        aiImageAnalysis: analysis,
      },
    };
    const shouldAutoDispatch = Boolean(analysis?.accidentDetected) && severityPercentage > AUTO_DISPATCH_SEVERITY_THRESHOLD;

    const emulation = await AccidentEmulation.create({
      createdBy: req.user._id,
      payload: reportPayload,
      status: "PendingApproval",
    });

    let accident = null;
    let dispatch = null;

    if (shouldAutoDispatch) {
      accident = await createAccidentAndTriggerWorkflow({
        payload: reportPayload,
        source: "manual",
      });

      emulation.status = "Approved";
      emulation.generatedAccidentId = accident._id;
      emulation.reviewedAt = new Date();
      await emulation.save();

      dispatch = await dispatchForAccident({
        accidentId: accident._id,
        reason: "Auto dispatch from high-severity citizen upload",
        assignedBy: "system",
      });

      emitToRole("admin", "emulation:reviewed", {
        emulationId: emulation._id,
        status: emulation.status,
        source: "citizen_upload",
      });
    } else {
      emitToRole("admin", "emulation:new", {
        emulationId: emulation._id,
        status: emulation.status,
        source: "citizen_upload",
      });
    }

    res.status(201).json({
      success: true,
      emulation,
      analysis,
      message: shouldAutoDispatch
        ? "Incident report automatically dispatched"
        : "Incident report submitted for admin approval",
    });
  } catch (error) {
    next(error);
  }
};

exports.getMyIncidentReports = async (req, res, next) => {
  try {
    const reports = await AccidentEmulation.find({
      createdBy: req.user._id,
      "payload.metadata.source": "citizen_upload",
    })
      .sort({ createdAt: -1 })
      .limit(50)
      .lean();

    res.json({ success: true, reports });
  } catch (error) {
    next(error);
  }
};
