const { validationResult } = require("express-validator");
const Response = require("../models/Response");
const Notification = require("../models/Notification");
const User = require("../models/User");
const ChatLog = require("../models/ChatLog");
const Accident = require("../models/Accident");
const SOSAlert = require("../models/SOSAlert");
const { stopSafetyTimer } = require("../services/timerService");
const { dispatchForAccident } = require("../services/dispatchService");
const { emitToRole, emitToUser } = require("../services/socketManager");
const { normalizeAddress, normalizeName, normalizePhone } = require("../utils/authValidation");

const createEmergencyContactSnapshot = (user) => ({
  name: normalizeName(user?.emergencyContact?.name || ""),
  phone: normalizePhone(user?.emergencyContact?.phone || ""),
});

exports.submitResponse = async (req, res, next) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({ success: false, errors: errors.array() });
    }

    const { accidentId, responseType, responseTimeMs } = req.body;

    const existing = await Response.findOne({ accidentId, userId: req.user._id });
    if (existing) {
      return res.status(409).json({ success: false, message: "Response already submitted" });
    }

    const response = await Response.create({
      accidentId,
      userId: req.user._id,
      responseType,
      responseTimeMs,
      autoGenerated: false,
    });

    await ChatLog.create({
      accidentId,
      userId: req.user._id,
      senderType: "user",
      message: responseType === "Help" ? "Need Help" : "I'm Safe",
      responseType,
    });

    stopSafetyTimer({ accidentId, userId: req.user._id });

    if (responseType === "Help") {
      const fallbackAddress = normalizeAddress(req.body.address || req.user?.address || "");

      if (fallbackAddress) {
        await Accident.findOneAndUpdate(
          { _id: accidentId, "location.address": { $in: [null, ""] } },
          { $set: { "location.address": fallbackAddress } }
        );
      }

      const introLog = await ChatLog.create({
        accidentId,
        userId: req.user._id,
        senderType: "system",
        message: "Admin support chat opened. Tell us what happened and what help you need.",
        responseType: "Chat",
      });

      emitToUser(req.user._id, "chat:message", { message: introLog });
      emitToRole("admin", "chat:message", { message: introLog });

      await dispatchForAccident({
        accidentId,
        reason: "User explicitly requested help",
        assignedBy: "system",
      });
    }

    const admins = await User.find({ role: "admin" }).select("_id");
    if (admins.length) {
      await Notification.insertMany(
        admins.map((u) => ({
          userId: u._id,
          accidentId,
          type: "SYSTEM",
          message: `User ${req.user.email} submitted response: ${responseType}`,
        }))
      );
    }

    emitToRole("admin", "response:received", { accidentId, userId: req.user._id, responseType });

    res.status(201).json({ success: true, response });
  } catch (error) {
    next(error);
  }
};

exports.getMyResponses = async (req, res, next) => {
  try {
    const responses = await Response.find({ userId: req.user._id })
      .populate("accidentId")
      .sort({ createdAt: -1 });

    res.json({ success: true, responses });
  } catch (error) {
    next(error);
  }
};

exports.triggerSOSAlert = async (req, res, next) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({ success: false, errors: errors.array() });
    }

    const latitude = Number(req.body.latitude);
    const longitude = Number(req.body.longitude);
    const address = normalizeAddress(req.body.address || req.user?.address || "");
    const emergencyContact = createEmergencyContactSnapshot(req.user);

    const accident = await Accident.create({
      location: {
        type: "Point",
        coordinates: [longitude, latitude],
        address,
      },
      severity: "High",
      confidenceScore: 1,
      source: "citizen_sos",
      metadata: {
        citizenSos: true,
        citizenUserId: req.user._id,
        citizenContact: {
          name: normalizeName(req.user?.name || ""),
          email: String(req.user?.email || "").trim().toLowerCase(),
          phone: normalizePhone(req.user?.phone || ""),
          address,
        },
        emergencyContact,
        source: "citizen_sos",
      },
    });

    const sosAlert = await SOSAlert.create({
      userId: req.user._id,
      accidentId: accident._id,
      location: { latitude, longitude, address },
      emergencyContact,
      message: req.body.message || "Citizen requested urgent help through SOS.",
    });

    const dispatch = await dispatchForAccident({
      accidentId: accident._id,
      reason: "Citizen triggered SOS alert",
      assignedBy: "system",
    });

    const introLog = await ChatLog.create({
      accidentId: accident._id,
      userId: req.user._id,
      senderType: "system",
      message: "SOS alert sent to admin. Support chat is ready.",
      responseType: "Chat",
    });

    const admins = await User.find({ role: "admin" }).select("_id");
    if (admins.length) {
      await Notification.insertMany(
        admins.map((u) => ({
          userId: u._id,
          accidentId: accident._id,
          type: "SYSTEM",
          message: `SOS alert from ${req.user.name || req.user.email}`,
        }))
      );
    }

    emitToUser(req.user._id, "chat:message", { message: introLog });
    emitToRole("admin", "chat:message", { message: introLog });
    emitToRole("admin", "sos:new", { sosAlertId: sosAlert._id, accidentId: accident._id, userId: req.user._id });

    res.status(201).json({ success: true, sosAlert, accident, dispatch, chatAccidentId: accident._id });
  } catch (error) {
    next(error);
  }
};
