const mongoose = require("mongoose");

const responseSchema = new mongoose.Schema(
  {
    accidentId: { type: mongoose.Schema.Types.ObjectId, ref: "Accident", required: true, index: true },
    userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },
    responseType: {
      type: String,
      enum: ["Safe", "Help", "No Response"],
      required: true,
    },
    responseTimeMs: { type: Number },
    autoGenerated: { type: Boolean, default: false },
  },
  { timestamps: true }
);

responseSchema.index({ accidentId: 1, userId: 1 }, { unique: true });

module.exports = mongoose.model("Response", responseSchema);
